# The gravity of the planets is relative to Minecraft's base gravity.

planets:
  world:
    gravity: 1.0
    hasAtmosphere: true
  mars:
    gravity: 0.38
    hasAtmosphere: false
  moon:
    gravity: 0.16
    hasAtmosphere: false

version: 1.0 # Do not touch this !